apiVersion: v1
kind: Service
metadata:
  name: svc-web
  namespace: openshift-3tiers
spec:
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
