# VM1 — Passerelle/Firewall
# Connectée à Internet, DMZ (192.168.100.0/24) et LAN (192.168.10.0/24)
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-firewall
  namespace: bienvenucloud-dev
  labels:
    app: firewall
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app: firewall
    spec:
      domain:
        cpu:
          cores: 1
        memory:
          guest: 1Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: dmz
              bridge: {}
            - name: lan
              bridge: {}
      networks:
        - name: default
          pod: {}
        - name: dmz
          multus:
            networkName: bienvenucloud-dev/dmz-network
        - name: lan
          multus:
            networkName: bienvenucloud-dev/lan-network
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm-firewall
              user: cloud-user
              password: openshift123
              chpasswd: { expire: False }

              runcmd:
                - apt-get update -y && apt-get install -y iptables iptables-persistent

                # Activer le routage IP
                - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
                - sysctl -p

                # Activer interfaces
                - ip link set enp2s0 up
                - ip link set enp3s0 up

                # Configuration IP
                - ip addr add 192.168.100.1/24 dev enp2s0
                - ip addr add 192.168.10.1/24 dev enp3s0

                # NAT vers Internet
                - iptables -t nat -A POSTROUTING -o enp1s0 -j MASQUERADE

                # Autoriser connexions établies
                - iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT

                # Internet → DMZ (HTTP)
                - iptables -A FORWARD -i enp1s0 -o enp2s0 -p tcp --dport 80 -j ACCEPT

                # DMZ → LAN (MySQL)
                - iptables -A FORWARD -i enp2s0 -o enp3s0 -p tcp --dport 3306 -j ACCEPT

                # Autoriser ICMP (ping)
                - iptables -A FORWARD -p icmp -j ACCEPT

                # Bloquer le reste
                - iptables -A FORWARD -j DROP

                # Sauvegarde
                - netfilter-persistent save

      terminationGracePeriodSeconds: 0
