# VM2 — Serveur Web (Nginx + Node.js)
# Connectée au réseau DMZ (192.168.100.0/24)
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-web
  namespace: bienvenucloud-dev
  labels:
    app: web
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app: web
    spec:
      domain:
        cpu:
          cores: 1
        memory:
          guest: 1Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: dmz
              bridge: {}           # Interface DMZ
      networks:
        - name: default
          pod: {}
        - name: dmz
          multus:
            networkName: bienvenucloud-dev/dmz-network    # UDN DMZ
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm-web
              user: cloud-user
              password: openshift123
              chpasswd: {expire: False}
              runcmd:
                # - apt-get update -y && apt-get install -y nginx nodejs --no-install-recommends
                # - systemctl enable nginx && systemctl start nginx
                # - ip addr add 192.168.100.10/24 dev eth1
                              # - ip link set eth1 up
                - apt-get update -y && apt-get install -y nginx nodejs netplan.io
              
                - |
                  cat <<EOF > /etc/netplan/01-netcfg.yaml
                  network:
                    version: 2
                    renderer: networkd
                    ethernets:
                      eth0:
                        dhcp4: true
                      eth1:
                        addresses:
                          - 192.168.100.10/24
                        gateway4: 192.168.100.1
                        nameservers:
                          addresses: [8.8.8.8, 1.1.1.1]
                  EOF
              
                - netplan apply
              
                - systemctl enable nginx
                - systemctl start nginx
                - curl -fsSL https://raw.githubusercontent.com/bienvenudiatta/openshift-3tiers/main/manifests/vms/index.html -o /var/www/html/index.html
      terminationGracePeriodSeconds: 0
