# VM2 — Serveur Web (Nginx + Node.js)
# Situé dans la DMZ — reçoit les requêtes HTTP depuis Internet via le firewall
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-web
  namespace: openshift-3tiers
  labels:
    app: web
spec:
  running: true
  template:
    metadata:
      labels:
        app: web
    spec:
      domain:
        cpu:
          cores: 1
        memory:
          guest: 1Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
          interfaces:
            - name: dmz
              bridge: {}           # Connectée uniquement à la DMZ
      networks:
        - name: dmz
          multus:
            networkName: dmz-network   # NAD créé dans 01-nad-dmz.yaml
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm-web
              packages:
                - nginx             # Serveur web
                - nodejs            # Runtime JavaScript
                - npm               # Gestionnaire de paquets Node.js
              runcmd:
                - systemctl enable nginx   # Nginx démarre automatiquement
                - systemctl start nginx    # Nginx démarre immédiatement
      terminationGracePeriodSeconds: 0
