apiVersion: v1
kind: Pod
metadata:
  name: pod-db
  namespace: bienvenucloud-dev
  labels:
    app: mysql
  annotations:
    k8s.v1.cni.cncf.io/networks: bienvenucloud-dev/lan-network
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root123
        - name: MYSQL_DATABASE
          value: appdb
        - name: MYSQL_USER
          value: appuser
        - name: MYSQL_PASSWORD
          value: apppassword123
      ports:
        - containerPort: 3306
